@host = http://localhost:3200

GET {{host}}/api/authors

###
GET {{host}}/api/authors/1

###
POST {{host}}/api/authors
Content-Type: application/json

{
    "name": "Juanan",
    "email": "juanan@mail.com",
    "image": "http://images.com/juanan.jpg"
}